### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by infinisil** [Tenchi2xh/Almonds#9]
Setting a license would be nice

**Comment by infinisil** [comment]
@Tenchi2xh Ping? Just a simple MIT license would probably be good, I'm mainly asking because I've packaged almonds for nixpkgs: https://github.com/NixOS/nixpkgs/pull/34169. And packages that don't have a license specified need to be declared as unfree. For Nix this means that users who didn't explicitly allow unfree software in their config won't be able to install it.

**Comment by Tenchi2xh** [comment]
Thanks for the ping, I meant to do it and forgot
I went with MIT for other projects, so I did that too here

Honored that you chose to add Almonds to an OS 😁
